sudo: required
services:
  - docker
before_install:
  - docker build -t bryankle/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true bryankle/docker-react npm run test
language: generic
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-706993973795"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY